export const Imageurl = 'https://lawmens-1.onrender.com';

export const backendroutes = {
  register: 'https://lawmens-1.onrender.com/api/v1/user/register',
  login: 'https://lawmens-1.onrender.com/api/v1/user/login',
  minorActList: 'https://lawmens-1.onrender.com/api/v1/minoract',
  signupConfig: 'https://lawmens-1.onrender.com/api/v1/user/signup-config',
  querySubmit: 'https://lawmens-1.onrender.com/api/v1/user/query',
  queryMy: 'https://lawmens-1.onrender.com/api/v1/user/query/my',
  otp: 'https://lawmens-1.onrender.com/api/v1/user/otp',
  verification: 'https://lawmens-1.onrender.com/api/v1/user/verification',
  profileverification: 'https://lawmens-1.onrender.com/api/v1/user/profileverification',
  forgotpassword: 'https://lawmens-1.onrender.com/api/v1/user/forgotpassword',
  getprofile: 'https://lawmens-1.onrender.com/api/v1/user/profile',
  category: 'https://lawmens-1.onrender.com/api/v1/category',
  casefilter: 'https://lawmens-1.onrender.com/api/v1/cases/casefilter',
  getSections: 'https://lawmens-1.onrender.com/api/v1/cases/getSections/',
  getSectioncontent: 'https://lawmens-1.onrender.com/api/v1/cases/getsectionContent/',
  bookmark: 'https://lawmens-1.onrender.com/api/v1/user/bookmark',
  share: 'https://lawmens-1.onrender.com/api/v1/cases/share/',
  google: 'https://lawmens-1.onrender.com/api/v1/user/google',
  subscription: 'https://lawmens-1.onrender.com/api/v1/subscription',
  plansubscribe: 'https://lawmens-1.onrender.com/api/v1/subscription/subscribe',
  userPlans: 'https://lawmens-1.onrender.com/api/v1/subscription/userPlans',
  privacypolicy: 'https://lawmens-1.onrender.com/api/v1/user/privacypolicy',
  getcatgories: 'https://lawmens-1.onrender.com/api/v1/profession',
  getSchedule: 'https://lawmens-1.onrender.com/api/v1/firstSchedule/getLegalEntries',
  getSecondSchedule: 'https://lawmens-1.onrender.com/api/v1/secondschedule/getLegalEntries',
  paymentsCreateOrder: 'https://lawmens-1.onrender.com/api/v1/payments/create-order',
  paymentsVerify: 'https://lawmens-1.onrender.com/api/v1/payments/verify-payment',
  paymentsVerifyMobile: 'https://lawmens-1.onrender.com/api/v1/payments/verify-mobile-purchase',
  comparison: 'https://lawmens-1.onrender.com/api/v1/cases/comparison/',
  notifications: 'https://lawmens-1.onrender.com/api/v1/user/notifications',
  fcmToken: 'https://lawmens-1.onrender.com/api/v1/user/fcm-token',
  subscriptionPlans: 'https://lawmens-1.onrender.com/api/v1/subscription/plans',
  verifyGooglePlay: 'https://lawmens-1.onrender.com/api/v1/subscription/verify-google-play',
  subscriptionStatus: 'https://lawmens-1.onrender.com/api/v1/subscription/status',
};

export const BASE_URL = 'https://lawmens-1.onrender.com/api/v1';
