export const RAZORPAY_KEY_ID = 'rzp_test_TVb8DvbczBMMAK';
export const Imageurl = 'https://lawmens-1.onrender.com';
export const BASE_URL = 'https://lawmens-1.onrender.com/api/v1';

export const backendroutes = {
  register: `${BASE_URL}/user/register`,
  login: `${BASE_URL}/user/login`,
  minorActList: `${BASE_URL}/minoract`,
  signupConfig: `${BASE_URL}/user/signup-config`,
  querySubmit: `${BASE_URL}/user/query`,
  queryMy: `${BASE_URL}/user/query/my`,
  otp: `${BASE_URL}/user/otp`,
  verification: `${BASE_URL}/user/verification`,
  profileverification: `${BASE_URL}/user/profileverification`,
  forgotpassword: `${BASE_URL}/user/forgotpassword`,
  getprofile: `${BASE_URL}/user/profile`,
  category: `${BASE_URL}/category`,
  casefilter: `${BASE_URL}/cases/casefilter`,
  getSections: `${BASE_URL}/cases/getSections/`,
  getSectioncontent: `${BASE_URL}/cases/getsectionContent/`,
  bookmark: `${BASE_URL}/user/bookmark`,
  share: `${BASE_URL}/cases/share/`,
  google: `${BASE_URL}/user/google`,
  subscription: `${BASE_URL}/subscription`,
  plansubscribe: `${BASE_URL}/subscription/subscribe`,
  userPlans: `${BASE_URL}/subscription/userPlans`,
  privacypolicy: `${BASE_URL}/user/privacypolicy`,
  getcatgories: `${BASE_URL}/profession`,
  getSchedule: `${BASE_URL}/firstSchedule/getLegalEntries`,
  getSecondSchedule: `${BASE_URL}/secondschedule/getLegalEntries`,
  paymentsCreateOrder: `${BASE_URL}/payments/create-order`,
  paymentsVerify: `${BASE_URL}/payments/verify-payment`,
  paymentsVerifyMobile: `${BASE_URL}/payments/verify-mobile-purchase`,
  comparison: `${BASE_URL}/cases/comparison/`,
  notifications: `${BASE_URL}/user/notifications`,
  fcmToken: `${BASE_URL}/user/fcm-token`,
  subscriptionPlans: `${BASE_URL}/subscription/plans`,
  verifyGooglePlay: `${BASE_URL}/subscription/verify-google-play`,
  subscriptionStatus: `${BASE_URL}/subscription/status`,
};
