rootProject.name = 'lawapp'
def getCliAndroidPath() {
    def f1 = file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
    if (f1.exists()) return f1
    return file("../node_modules/react-native/node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
}
apply from: getCliAndroidPath(); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')
