const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
require('dotenv').config();

const Casebook = require('../src/models/casebookmaster');
const Category = require('../src/models/category');

const MONGO_URI = process.env.DBURL || "mongodb+srv://thelawmenslex_db_user:Lawmens%40lex@cluster0.ddwnq8e.mongodb.net/lawapp?retryWrites=true&w=majority&appName=Cluster0";

// Dictionary of full chapter titles mapped by Prefix / Roman Numerals
const IPC_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II GENERAL EXPLANATIONS",
    "CHAPTER III ": "CHAPTER III OF PUNISHMENTS",
    "CHAPTER IV ": "CHAPTER IV GENERAL EXCEPTIONS",
    "CHAPTER V ": "CHAPTER V OF ABETMENT",
    "CHAPTER VA ": "CHAPTER VA CRIMINAL CONSPIRACY",
    "CHAPTER VI ": "CHAPTER VI OF OFFENCES AGAINST THE STATE",
    "CHAPTER VII ": "CHAPTER VII OF OFFENCES RELATING TO THE ARMY, NAVY AND AIR FORCE",
    "CHAPTER VIII ": "CHAPTER VIII OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY",
    "CHAPTER IX ": "CHAPTER IX OF OFFENCES BY OR RELATING TO PUBLIC SERVANTS",
    "CHAPTER IXA ": "CHAPTER IXA OF OFFENCES RELATING TO ELECTIONS",
    "CHAPTER X ": "CHAPTER X OF CONTEMPTS OF THE LAWFUL AUTHORITY OF PUBLIC SERVANTS",
    "CHAPTER XI ": "CHAPTER XI OF FALSE EVIDENCE AND OFFENCES AGAINST PUBLIC JUSTICE",
    "CHAPTER XII ": "CHAPTER XII OF OFFENCES RELATING TO COIN AND GOVERNMENT STAMPS",
    "CHAPTER XIII ": "CHAPTER XIII OF OFFENCES RELATING TO WEIGHTS AND MEASURES",
    "CHAPTER XIV ": "CHAPTER XIV OF OFFENCES AFFECTING THE PUBLIC HEALTH, SAFETY, CONVENIENCE, DECENCY AND MORALS",
    "CHAPTER XV ": "CHAPTER XV OF OFFENCES RELATING TO RELIGION",
    "CHAPTER XVI ": "CHAPTER XVI OF OFFENCES AFFECTING THE HUMAN BODY",
    "CHAPTER XVII ": "CHAPTER XVII OF OFFENCES AGAINST PROPERTY",
    "CHAPTER XVIII ": "CHAPTER XVIII OF OFFENCES RELATING TO DOCUMENTS AND TO PROPERTY MARKS",
    "CHAPTER XIX ": "CHAPTER XIX OF THE CRIMINAL BREACH OF CONTRACTS OF SERVICE",
    "CHAPTER XX ": "CHAPTER XX OF OFFENCES RELATING TO MARRIAGE",
    "CHAPTER XXA ": "CHAPTER XXA OF CRUELTY BY HUSBAND OR RELATIVES OF HUSBAND",
    "CHAPTER XXI ": "CHAPTER XXI OF DEFAMATION",
    "CHAPTER XXII ": "CHAPTER XXII OF CRIMINAL INTIMIDATION, INSULT AND ANNOYANCE",
    "CHAPTER XXIII ": "CHAPTER XXIII OF ATTEMPTS TO COMMIT OFFENCES"
};

const BNS_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II OF PUNISHMENTS",
    "CHAPTER III ": "CHAPTER III GENERAL EXCEPTIONS",
    "CHAPTER IV ": "CHAPTER IV OF ABETMENT, CRIMINAL CONSPIRACY AND ATTEMPT",
    "CHAPTER V ": "CHAPTER V OF OFFENCES AGAINST WOMEN AND CHILDREN",
    "CHAPTER VI ": "CHAPTER VI OF OFFENCES AFFECTING THE HUMAN BODY",
    "CHAPTER VII ": "CHAPTER VII OF OFFENCES AGAINST THE STATE",
    "CHAPTER VIII ": "CHAPTER VIII OF OFFENCES RELATING TO THE ARMED FORCES",
    "CHAPTER IX ": "CHAPTER IX OF OFFENCES RELATING TO ELECTIONS",
    "CHAPTER X ": "CHAPTER X OF OFFENCES RELATING TO COIN, CURRENCY-NOTES, BANK-NOTES AND GOVERNMENT STAMPS",
    "CHAPTER XI ": "CHAPTER XI OF OFFENCES AGAINST PUBLIC TRANQUILLITY",
    "CHAPTER XII ": "CHAPTER XII OF OFFENCES BY OR RELATING TO PUBLIC SERVANTS",
    "CHAPTER XIII ": "CHAPTER XIII OF CONTEMPTS OF THE LAWFUL AUTHORITY OF PUBLIC SERVANTS",
    "CHAPTER XIV ": "CHAPTER XIV OF FALSE EVIDENCE AND OFFENCES AGAINST PUBLIC JUSTICE",
    "CHAPTER XV ": "CHAPTER XV OF OFFENCES AFFECTING THE PUBLIC HEALTH, SAFETY, CONVENIENCE, DECENCY AND MORALS",
    "CHAPTER XVI ": "CHAPTER XVI OF OFFENCES RELATING TO RELIGION",
    "CHAPTER XVII ": "CHAPTER XVII OF OFFENCES AGAINST PROPERTY",
    "CHAPTER XVIII ": "CHAPTER XVIII OF OFFENCES RELATING TO DOCUMENTS AND TO PROPERTY MARKS",
    "CHAPTER XIX ": "CHAPTER XIX OF CRIMINAL INTIMIDATION, INSULT, ANNOYANCE, DEFAMATION, ETC."
};

const CrPC_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II CONSTITUTION OF CRIMINAL COURTS AND OFFICES",
    "CHAPTER III ": "CHAPTER III POWER OF COURTS",
    "CHAPTER IV ": "CHAPTER IV POWERS OF SUPERIOR OFFICERS OF POLICE; AND AID TO MAGISTRATES AND POLICE",
    "CHAPTER IV A": "CHAPTER IV A.—POWERS OF SUPERIOR OFFICERS OF POLICE; B.—AID TO THE MAGISTRATES AND THE POLICE",
    "CHAPTER V ": "CHAPTER V ARREST OF PERSONS",
    "CHAPTER VI ": "CHAPTER VI PROCESSES TO COMPEL APPEARANCE",
    "CHAPTER VII ": "CHAPTER VII PROCESSES TO COMPEL THE PRODUCTION OF THINGS",
    "CHAPTER VIIA ": "CHAPTER VIIA RECIPROCAL ARRANGEMENTS FOR ASSISTANCE IN CERTAIN MATTERS AND PROCEDURE FOR ATTACHMENT AND FORFEITURE OF PROPERTY",
    "CHAPTER VIII ": "CHAPTER VIII SECURITY FOR KEEPING THE PEACE AND FOR GOOD BEHAVIOUR",
    "CHAPTER IX ": "CHAPTER IX ORDER FOR MAINTENANCE OF WIVES, CHILDREN AND PARENTS",
    "CHAPTER X ": "CHAPTER X MAINTENANCE OF PUBLIC ORDER AND TRANQUILLITY",
    "CHAPTER XI ": "CHAPTER XI PREVENTIVE ACTION OF THE POLICE",
    "CHAPTER XII ": "CHAPTER XII INFORMATION TO THE POLICE AND THEIR POWERS TO INVESTIGATE",
    "CHAPTER XIII ": "CHAPTER XIII JURISDICTION OF THE CRIMINAL COURTS IN INQUIRIES AND TRIALS",
    "CHAPTER XIV ": "CHAPTER XIV CONDITIONS REQUISITE FOR INITIATION OF PROCEEDINGS",
    "CHAPTER XV ": "CHAPTER XV COMPLAINTS TO MAGISTRATES",
    "CHAPTER XVI ": "CHAPTER XVI COMMENCEMENT OF PROCEEDINGS BEFORE MAGISTRATES",
    "CHAPTER XVII ": "CHAPTER XVII THE CHARGE",
    "CHAPTER XVIII ": "CHAPTER XVIII TRIAL BEFORE A COURT OF SESSION",
    "CHAPTER XIX ": "CHAPTER XIX TRIAL OF WARRANT-CASES BY MAGISTRATES",
    "CHAPTER XX ": "CHAPTER XX TRIAL OF SUMMONS-CASES BY MAGISTRATES",
    "CHAPTER XXI ": "CHAPTER XXI SUMMARY TRIALS",
    "CHAPTER XXI A": "CHAPTER XXI A PLEA BARGAINING",
    "CHAPTER XXII ": "CHAPTER XXII ATTENDANCE OF PERSONS CONFINED OR DETAINED IN PRISONS",
    "CHAPTER XXIII ": "CHAPTER XXIII EVIDENCE IN INQUIRIES AND TRIALS",
    "CHAPTER XXIV ": "CHAPTER XXIV GENERAL PROVISIONS AS TO INQUIRIES AND TRIALS",
    "CHAPTER XXV ": "CHAPTER XXV PROVISIONS AS TO ACCUSED PERSONS OF UNSOUND MIND",
    "CHAPTER XXVI ": "CHAPTER XXVI PROVISIONS AS TO OFFENCES AFFECTING THE ADMINISTRATION OF JUSTICE",
    "CHAPTER XXVII ": "CHAPTER XXVII THE JUDGMENT",
    "CHAPTER XXVIII ": "CHAPTER XXVIII SUBMISSION OF DEATH SENTENCES FOR CONFIRMATION",
    "CHAPTER XXIX ": "CHAPTER XXIX APPEALS",
    "CHAPTER XXX ": "CHAPTER XXX REFERENCE AND REVISION",
    "CHAPTER XXXI ": "CHAPTER XXXI TRANSFER OF CRIMINAL CASES",
    "CHAPTER XXXII ": "CHAPTER XXXII EXECUTION, SUSPENSION, REMISSION AND COMMUTATION OF SENTENCES",
    "CHAPTER XXXIII ": "CHAPTER XXXIII PROVISIONS AS TO BAIL AND BONDS",
    "CHAPTER XXXIV ": "CHAPTER XXXIV DISPOSAL OF PROPERTY",
    "CHAPTER XXXV ": "CHAPTER XXXV IRREGULAR PROCEEDINGS",
    "CHAPTER XXXVI ": "CHAPTER XXXVI LIMITATION FOR TAKING COGNIZANCE OF CERTAIN OFFENCES",
    "CHAPTER XXXVII ": "CHAPTER XXXVII MISCELLANEOUS"
};

const BNSS_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II CONSTITUTION OF CRIMINAL COURTS AND OFFICES",
    "CHAPTER III ": "CHAPTER III POWER OF COURTS",
    "CHAPTER IV ": "CHAPTER IV POWERS OF SUPERIOR OFFICERS OF POLICE AND AID TO THE MAGISTRATES AND THE POLICE",
    "CHAPTER V ": "CHAPTER V ARREST OF PERSONS",
    "CHAPTER VI ": "CHAPTER VI PROCESSES TO COMPEL APPEARANCE",
    "CHAPTER VII ": "CHAPTER VII PROCESSES TO COMPEL THE PRODUCTION OF THINGS",
    "CHAPTER VIII ": "CHAPTER VIII RECIPROCAL ARRANGEMENTS FOR ASSISTANCE IN CERTAIN MATTERS AND PROCEDURE FOR ATTACHMENT AND FORFEITURE OF PROPERTY",
    "CHAPTER IX ": "CHAPTER IX SECURITY FOR KEEPING THE PEACE AND FOR GOOD BEHAVIOUR",
    "CHAPTER X ": "CHAPTER X ORDER FOR MAINTENANCE OF WIVES, CHILDREN AND PARENTS",
    "CHAPTER XI ": "CHAPTER XI MAINTENANCE OF PUBLIC ORDER AND TRANQUILLITY",
    "CHAPTER XII ": "CHAPTER XII PREVENTIVE ACTION OF THE POLICE",
    "CHAPTER XIII ": "CHAPTER XIII INFORMATION TO THE POLICE AND THEIR POWERS TO INVESTIGATE",
    "CHAPTER XIV ": "CHAPTER XIV JURISDICTION OF THE CRIMINAL COURTS IN INQUIRIES AND TRIALS",
    "CHAPTER XV ": "CHAPTER XV CONDITIONS REQUISITE FOR INITIATION OF PROCEEDINGS",
    "CHAPTER XVI ": "CHAPTER XVI COMPLAINTS TO MAGISTRATES",
    "CHAPTER XVII ": "CHAPTER XVII COMMENCEMENT OF PROCEEDINGS BEFORE MAGISTRATES",
    "CHAPTER XVIII ": "CHAPTER XVIII THE CHARGE",
    "CHAPTER XIX ": "CHAPTER XIX TRIAL BEFORE A COURT OF SESSION",
    "CHAPTER XX ": "CHAPTER XX TRIAL OF WARRANT-CASES BY MAGISTRATES",
    "CHAPTER XXI ": "CHAPTER XXI TRIAL OF SUMMONS-CASES BY MAGISTRATES",
    "CHAPTER XXII ": "CHAPTER XXII SUMMARY TRIALS",
    "CHAPTER XXIII ": "CHAPTER XXIII PLEA BARGAINING",
    "CHAPTER XXIV ": "CHAPTER XXIV ATTENDANCE OF PERSONS CONFINED OR DETAINED IN PRISONS",
    "CHAPTER XXV ": "CHAPTER XXV EVIDENCE IN INQUIRIES AND TRIALS",
    "CHAPTER XXVI ": "CHAPTER XXVI GENERAL PROVISIONS AS TO INQUIRIES AND TRIALS",
    "CHAPTER XXVII ": "CHAPTER XXVII PROVISIONS AS TO ACCUSED PERSONS OF UNSOUND MIND",
    "CHAPTER XXVIII ": "CHAPTER XXVIII PROVISIONS AS TO OFFENCES AFFECTING THE ADMINISTRATION OF JUSTICE",
    "CHAPTER XXIX ": "CHAPTER XXIX THE JUDGMENT",
    "CHAPTER XXX ": "CHAPTER XXX SUBMISSION OF DEATH SENTENCES FOR CONFIRMATION",
    "CHAPTER XXXI ": "CHAPTER XXXI APPEALS",
    "CHAPTER XXXII ": "CHAPTER XXXII REFERENCE AND REVISION",
    "CHAPTER XXXIII ": "CHAPTER XXXIII TRANSFER OF CRIMINAL CASES",
    "CHAPTER XXXIV ": "CHAPTER XXXIV EXECUTION, SUSPENSION, REMISSION AND COMMUTATION OF SENTENCES",
    "CHAPTER XXXV ": "CHAPTER XXXV PROVISIONS AS TO BAIL AND BONDS",
    "CHAPTER XXXVI ": "CHAPTER XXXVI DISPOSAL OF PROPERTY",
    "CHAPTER XXXVII ": "CHAPTER XXXVII IRREGULAR PROCEEDINGS",
    "CHAPTER XXXVIII ": "CHAPTER XXXVIII LIMITATION FOR TAKING COGNIZANCE OF CERTAIN OFFENCES",
    "CHAPTER XXXIX ": "CHAPTER XXXIX MISCELLANEOUS"
};

const IEA_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II OF THE RELEVANCY OF FACTS",
    "CHAPTER III ": "CHAPTER III FACTS WHICH NEED NOT BE PROVED",
    "CHAPTER IV": "CHAPTER IV OF ORAL EVIDENCE",
    "CHAPTER V": "CHAPTER V OF DOCUMENTARY EVIDENCE",
    "CHAPTER VI": "CHAPTER VI OF THE EXCLUSION OF ORAL BY DOCUMENTARY EVIDENCE",
    "CHAPTER VII": "CHAPTER VII OF THE BURDEN OF PROOF",
    "CHAPTER VIII": "CHAPTER VIII ESTOPPEL",
    "CHAPTER IX": "CHAPTER IX OF WITNESSES",
    "CHAPTER X": "CHAPTER X OF THE EXAMINATION OF WITNESSES",
    "CHAPTER XI": "CHAPTER XI OF IMPROPER ADMISSION AND REJECTION OF EVIDENCE"
};

const BSA_MAP = {
    "CHAPTER I ": "CHAPTER I PRELIMINARY",
    "CHAPTER II ": "CHAPTER II RELEVANCY OF FACTS",
    "CHAPTER III ": "CHAPTER III FACTS WHICH NEED NOT BE PROVED",
    "CHAPTER IV": "CHAPTER IV OF ORAL EVIDENCE",
    "CHAPTER V": "CHAPTER V OF DOCUMENTARY EVIDENCE",
    "CHAPTER VI": "CHAPTER VI OF THE EXCLUSION OF ORAL BY DOCUMENTARY EVIDENCE",
    "CHAPTER VII": "CHAPTER VII OF THE BURDEN OF PROOF",
    "CHAPTER VIII": "CHAPTER VIII ESTOPPEL",
    "CHAPTER IX": "CHAPTER IX OF WITNESSES",
    "CHAPTER X": "CHAPTER X OF EXAMINATION OF WITNESSES",
    "CHAPTER XI": "CHAPTER XI OF IMPROPER ADMISSION AND REJECTION OF EVIDENCE",
    "CHAPTER XII": "CHAPTER XII REPEAL AND SAVINGS"
};

async function fix() {
    try {
        await mongoose.connect(MONGO_URI);
        console.log("Connected to MongoDB.");

        const casebooks = await Casebook.find().populate('categoryId').lean();
        let updatedCount = 0;

        for (const cb of casebooks) {
            const catName = cb.categoryId ? cb.categoryId.name : '';
            let mapToUse = null;

            if (catName.includes("Penal Code") || catName.includes("IPC")) {
                mapToUse = IPC_MAP;
            } else if (catName.includes("Nyaya Sanhita") || catName.includes("BNS")) {
                mapToUse = BNS_MAP;
            } else if (catName.includes("Criminal Procedure") || catName.includes("CrPC")) {
                mapToUse = CrPC_MAP;
            } else if (catName.includes("Nagarik Suraksha") || catName.includes("BNSS")) {
                mapToUse = BNSS_MAP;
            } else if (catName.includes("Evidence Act") || catName.includes("IEA")) {
                mapToUse = IEA_MAP;
            } else if (catName.includes("Sakshya Adhiniyam") || catName.includes("BSA")) {
                mapToUse = BSA_MAP;
            }

            if (!mapToUse || !cb.name) continue;

            // Match full chapter name by prefix (e.g. "CHAPTER XVII ")
            const currentNameUpper = cb.name.toUpperCase().trim();
            let matchedFullName = null;

            // Sort keys by length descending to match longer prefixes first (e.g. CHAPTER XVII vs CHAPTER X)
            const keys = Object.keys(mapToUse).sort((a, b) => b.length - a.length);
            for (const key of keys) {
                const keyClean = key.toUpperCase().trim();
                if (currentNameUpper.startsWith(keyClean)) {
                    matchedFullName = mapToUse[key];
                    break;
                }
            }

            if (matchedFullName && matchedFullName !== cb.name) {
                console.log(`[Updating] ID ${cb._id} (${catName}):\n  OLD: "${cb.name}"\n  NEW: "${matchedFullName}"`);
                await Casebook.updateOne({ _id: cb._id }, { $set: { name: matchedFullName } });
                updatedCount++;
            }
        }

        console.log(`\nSuccessfully updated ${updatedCount} truncated chapter titles in MongoDB!`);
        mongoose.connection.close();
    } catch (e) {
        console.error(e);
    }
}

fix();
